name: translations_manager
description: Package to manage translations files in json format
version: 0.0.2
repository: https://github.com/mevluttosun/translations_manager.git

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  args: ^2.3.1
  glob: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
